#################################################################################
# Attention:           THIS FILE MUST BE IN UNIX Text Format
#
# Makefile for AutoRegisterScout.dll
#
# This Makefile works only with:
#    - gnu make.exe and unix sh.exe ( please use: idea_make --unix -f Makefile)
#    - cygwin tools ( with $SHELLHOME )
#
# generated by CreateMakefile.bash from X:/n4_prod/x86/prod/release/share/MrServers/MrImaging/seq/a_gre/Makefile.gre
# TBC
# example call:
# idea_make --unix -f Makefile.mk clean all
#################################################################################


all : release debug i86Release

release: dllRelease
debug:   dllDebug
#************************************************************************
# add myself to dependency list
#************************************************************************
MAKEFILE_CHAIN += AutoRegisterScout.mk


#************************************************************************
# Target naming
#************************************************************************

TARGET_NAME = AutoRegisterScout
LIB_NAME    = AutoRegisterScout



#************************************************************************
# Sources and destinations
#************************************************************************


# alternative valid notation: 
# SOURCES  = file1.cpp
# SOURCES += file2.cpp
# SOURCES += ../multipleUsed.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/SBBGREKernel.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/SBBReadOut.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/SBBPhaseEncode.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/LocalSeqLoop.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/AutoRegisterScout.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/iPAT.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/AffineTransformReceiver.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/../common/CT/CT.cpp
SOURCES += ${IDEA_BASE}/n4/pkg/MrServers/MrImaging/seq/AutoRegisterScout/../common/CT/CT_UI.cpp

#************************************************************************
# Target specific CPPFLAGS
#************************************************************************


CPPFLAGS_LOCAL += -D_CONSOLE
CPPFLAGS_LOCAL += -DGRE
CPPFLAGS_LOCAL += -DBUILD_SEQU
CPPFLAGS_LOCAL += -DSUPPORT_PACE
CPPFLAGS_LOCAL += -DSUPPORT_iPAT
CPPFLAGS_LOCAL += -DNOCRYPT
CPPFLAGS_LOCAL += -DSUPPORT_CT

#************************************************************************
# LIBs
#************************************************************************


LDLIBS += libUILink.lib
LDLIBS += MrProt.lib
LDLIBS += Sequence.lib
LDLIBS += MeasSections.lib
LDLIBS += PerProxies.lib
LDLIBS += libSBB.lib
LDLIBS += libSSL.lib
LDLIBS += libRT.lib
LDLIBS += libGSL.lib
LDLIBS += SeqBuffer.lib
LDLIBS += libSeqUtil.lib
LDLIBS += libSeqUT.lib
LDLIBS += libUICtrl.lib
LDLIBS += CoilIF.lib
LDLIBS += MrTrace.lib
LDLIBS += MeasNucleiBase.lib
LDLIBS += libPACE.lib

#************************************************************************
# INCLUDE General rules for sequences
#************************************************************************


include $(IDEA_BASE)/n4/pkg/MrApplications/MrIDEA/utils/MakeSeq.mk


