##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
##
## Project: NUMARIS/4
##    File: \n4\pkg\MrServers\MrImaging\seq\AutoRegisterScout\makefile.trs
## Version:
##  Author: KUEHN
##    Date: n.a.
##
##    Lang: make
##
## Descrip: Makefile fuer Sequenz-DLL
##
##-----------------------------------------------------------------------------

##-----------------------------------------------------------------------------
## Naehere Informationen zum den moeglichen Macros im Makefile siehe
## MedMake-Dokumentation Q:/csw/MedMake/html/contents_t6.html
##

##-----------------------------------------------------------------------------
## enter local compiler flags
##
CPPFLAGS (-D_CONSOLE)
CPPFLAGS (-DGRE)
CPPFLAGS (-DBUILD_SEQU)
CPPFLAGS (-DSUPPORT_PACE)
CPPFLAGS (-DSUPPORT_iPAT)
CPPFLAGS (-DNOCRYPT)
CPPFLAGS (-DSUPPORT_CT)

##-----------------------------------------------------------------------------
## enter include paths
##

##-----------------------------------------------------------------------------
## enter source files
##
CPPSOURCES (SBBGREKernel)
CPPSOURCES (SBBReadOut)
CPPSOURCES (SBBPhaseEncode)
CPPSOURCES (LocalSeqLoop)
CPPSOURCES (AutoRegisterScout)
CPPSOURCES (iPAT)
CPPSOURCES (AffineTransformReceiver)

## sources needed, if SUPPORT_CT is defined
CPPSOURCESFROM (CT,../common/CT)
CPPSOURCESFROM (CT_UI,../common/CT)
##-----------------------------------------------------------------------------
## enter local linker flags
##

##-----------------------------------------------------------------------------
## enter link libraries
##    
LDLIBS (libUILink)
LDLIBS (MrProt)
LDLIBS (Sequence)
LDLIBS (MeasSections)
LDLIBS (PerProxies)
LDLIBS (libSBB)
LDLIBS (libSSL)
LDLIBS (libRT)
LDLIBS (libGSL)
LDLIBS (SeqBuffer)
LDLIBS (libSeqUtil)
LDLIBS (libSeqUT)
LDLIBS (libUICtrl)
LDLIBS (CoilIF)
LDLIBS (MrTrace)
LDLIBS (MeasNucleiBase)
LDLIBS (libPACE)

##-----------------------------------------------------------------------------
## enter target name
##
LIB(AutoRegisterScout)

##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
